# -*- coding: utf-8 -*-
"""love.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Puv1SWMKsF9LHA9aBp8cS0S9JhemvNVZ

# 환경설정
"""

# =========================================================
# [1단계] 라이브러리 설치 및 런타임 강제 재시작
# =========================================================
import os

print("1. 필수 라이브러리 설치 중...")
!pip uninstall mediapipe -y
!pip install mediapipe==0.10.14

print("2. 한글 폰트 설치 중...")
!sudo apt-get install -y fonts-nanum
!sudo fc-cache -fv
!rm ~/.cache/matplotlib -rf

print("✅ 설치 완료. 런타임을 강제로 재시작합니다...")
print("⚠️ 잠시 후 '세션이 다운되었습니다' 경고가 뜨면 정상이니 닫고 [2단계]를 실행하세요.")

# 1. YOLO(ultralytics) 및 MediaPipe 설치
!pip install ultralytics mediapipe

# 2. 한글 폰트 설치 (시각화에 필요)
!sudo apt-get install -y fonts-nanum
!sudo fc-cache -fv
!rm ~/.cache/matplotlib -rf

print("✅ 모든 라이브러리 설치가 완료되었습니다.")

# 1. 기존 충돌 가능성이 있는 라이브러리들을 싹 지웁니다.
!pip uninstall -y torch torchvision torchaudio triton ultralytics

# 2. 호환되는 버전으로 다시 깔끔하게 설치합니다.
!pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu121
!pip install ultralytics mediapipe

# 3. 한글 폰트 (시각화용)
!sudo apt-get install -y fonts-nanum
!rm ~/.cache/matplotlib -rf

"""# 궁합"""

import cv2
import numpy as np
import matplotlib.pyplot as plt
from ultralytics import YOLO
import mediapipe as mp
from PIL import ImageFont, ImageDraw, Image
from google.colab import drive, files
import os
import math
import random
from IPython.display import display, HTML
import base64
from io import BytesIO

# 1. 미디어파이프 및 드라이브 설정
try:
    mp_hands = mp.solutions.hands
except AttributeError:
    print("🚨 오류: 런타임 재시작이 필요합니다.")
    raise

if not os.path.exists('/content/drive'):
    drive.mount('/content/drive')

# =========================================================
# [V23.0] 커플 궁합 해석기 (풍성한 Love Tip & 콘텐츠 강화)
# =========================================================
class CompatibilityInterpreter:
    def __init__(self):
        # 1. 메인 텍스트 DB (기존 유지 - 2점 단위 정밀 분석)
        self.high_score_db = {
            # [90점대]
            49: {'title': "🦄 전설 속의 유니콘", 'desc': "이건 사람이 맺은 인연이 아닙니다. 우주가 도왔네요. 전생에 최소 3번은 부부였을 겁니다.", 'tag': "#신계영역 #기적 #완벽그자체"},
            48: {'title': "👑 왕과 여왕의 만남", 'desc': "서로를 빛내주기 위해 태어난 존재들입니다. 감정선이 마치 복사한 듯 일치합니다.", 'tag': "#퍼펙트매치 #소울메이트"},
            47: {'title': "💍 결혼이 시급합니다", 'desc': "더 이상 잴 필요도 없습니다. 눈빛만 봐도 통하는 사이, 놓치면 평생 땅을 치고 후회할 운명입니다.", 'tag': "#결혼각 #운명 #평생내편"},
            46: {'title': "💞 심장이 반응하는 사이", 'desc': "머리로 생각하기 전에 가슴이 먼저 반응합니다. 서로에게 가장 포근한 안식처가 되어주는군요.", 'tag': "#심쿵 #안식처 #힐링"},
            45: {'title': "🌹 로맨스 소설 주인공", 'desc': "드라마나 영화에서 보던 사랑이 현실이 되었습니다. 주위 사람들이 부러워할 만큼 예쁜 사랑 중이네요.", 'tag': "#로맨틱 #성공적 #워너비"},
            # [80점대]
            44: {'title': "🍯 달달한 양봉업자", 'desc': "눈에서 꿀이 뚝뚝 떨어집니다. 서로의 단점조차 귀여워 보이는 '콩깍지'가 평생 갈 기세입니다.", 'tag': "#꿀뚝뚝 #콩깍지 #달달함"},
            43: {'title': "🍬 솜사탕 같은 사랑", 'desc': "함께 있으면 세상이 달콤해집니다. 싸워도 금방 풀리고, 뒤끝 없이 깨끗하고 맑은 연애를 하고 계시네요.", 'tag': "#스윗함 #순수 #청정구역"},
            42: {'title': "🔒 단단한 자물쇠", 'desc': "흔들리지 않는 편안함! 서로에 대한 신뢰가 매우 두터워 어떤 시련이 와도 끄떡없을 단단한 사이입니다.", 'tag': "#신뢰 #굳건함 #믿음"},
            41: {'title': "🔥 불타는 금요일", 'desc': "열정이 넘치는 커플입니다. 함께 무언가를 할 때 에너지가 폭발하며, 지루할 틈이 없는 익사이팅한 관계!", 'tag': "#열정 #에너지 #활력소"},
            40: {'title': "🧱 든든한 내 편", 'desc': "세상 모두가 등을 돌려도 이 사람만은 내 편이 되어줄 겁니다. 아주 안정적이고 모범적인 커플의 정석입니다.", 'tag': "#내편 #안정감 #정석"},
            # [70점대]
            39: {'title': "🌱 자라나는 새싹", 'desc': "서로가 서로의 성장을 돕는 '비료' 같은 존재입니다. 함께할수록 더 멋진 사람이 되어가는 생산적인 관계!", 'tag': "#성장형 #윈윈 #미래지향"},
            38: {'title': "🧩 딱 맞는 퍼즐", 'desc': "성격은 조금 다를지 몰라도, 가치관이 잘 맞습니다. 서로의 빈틈을 기가 막히게 채워주는 상호보완적 관계입니다.", 'tag': "#퍼즐 #상호보완 #밸런스"},
            37: {'title': "🥂 샴페인 커플", 'desc': "톡 쏘는 매력이 있습니다. 가끔 의견 차이가 있어도 대화로 쿨하게 풀어내는 성숙함을 갖추고 있네요.", 'tag': "#쿨함 #성숙 #매력"},
            36: {'title': "🎨 물감과 붓", 'desc': "서로 다른 색깔을 가졌지만, 둘이 만나 아름다운 그림을 그립니다. 다름을 인정하고 즐길 줄 아는 멋진 커플.", 'tag': "#조화 #예술 #컬러풀"},
            35: {'title': "👟 편안한 운동화", 'desc': "오래 신은 신발처럼 편안합니다. 격식 차릴 필요 없이 가장 '나다운 모습'을 보여줄 수 있는 베스트 프렌드.", 'tag': "#베프 #편안함 #자연스러움"}
        }
        self.default_text = {
            'title': "⚡ 짜릿한 스파크", 'desc': "서로 너무 달라서 미친 듯이 끌리는 자석 같은 사이! 매일매일이 예측불허인 스펙터클한 로맨스입니다.", 'tag': "#반전매력 #자석 #달콤살벌"
        }

        # 2. [NEW] Love Tip 심화 DB (점수 구간별 추천)
        self.tips_db = {
            'tier_1': [ # 90점 이상 (소울메이트/결혼)
                {'mission': "서로의 미래 일기 써주기 (1년 뒤 오늘)", 'item': "이니셜이 새겨진 커플링 또는 각인 팔찌", 'place': "프라이빗한 호캉스나 조용한 와인바"},
                {'mission': "눈을 1분간 바라보며 사랑한다고 말하기", 'item': "두 분의 추억이 담긴 포토북 제작", 'place': "야경이 한눈에 보이는 전망대"},
                {'mission': "서로의 발 씻겨주기 (세족식)", 'item': "같은 향을 공유하는 커플 향수", 'place': "둘만의 오붓한 글램핑장"},
                {'mission': "함께 통장 개설하거나 재테크 계획 세우기", 'item': "잠옷(파자마) 세트 맞춰 입기", 'place': "분위기 좋은 재즈바"}
            ],
            'tier_2': [ # 80점대 (달달함/안정)
                {'mission': "서로에게 어울리는 옷 골라주기", 'item': "귀여운 커플 폰케이스", 'place': "놀이공원 교복 데이트"},
                {'mission': "도시락 싸서 피크닉 가기", 'item': "커플 운동화 (스니커즈)", 'place': "한강 공원 텐트 데이트"},
                {'mission': "함께 요리해서 저녁 먹기", 'item': "서로의 탄생석이 들어간 키링", 'place': "쿠킹 클래스 또는 도자기 공방"},
                {'mission': "네 컷 사진 찍으며 엽기 표정 짓기", 'item': "맨투맨 티셔츠 시밀러룩", 'place': "힙한 성수동 카페 투어"}
            ],
            'tier_3': [ # 70점대 (친구/성장)
                {'mission': "밤새도록 술 한잔하며 진지한 대화하기", 'item': "커플 모자 (볼캡/비니)", 'place': "조용한 룸 이자카야"},
                {'mission': "서로의 취미 생활 하루 동안 같이 해보기", 'item': "블루투스 이어폰 케이스 세트", 'place': "함께 땀 흘리는 등산이나 클라이밍"},
                {'mission': "서로에게 추천하고 싶은 책 선물하기", 'item': "스마트워치 스트랩 맞추기", 'place': "대형 서점 데이트"},
                {'mission': "맛집 웨이팅 기다리며 수다 떨기", 'item': "커플 텀블러", 'place': "줄 서서 먹는 핫플레이스 맛집"}
            ],
            'tier_4': [ # 그 외 (스파크/이색)
                {'mission': "방탈출 게임에서 협동심 기르기", 'item': "재미있는 문구가 적힌 티셔츠", 'place': "공포 테마 방탈출 카페"},
                {'mission': "서로의 MBTI 분석해주기", 'item': "필름 카메라 (서로 찍어주기)", 'place': "레트로 감성 롤러장"},
                {'mission': "노래방 가서 스트레스 풀기", 'item': "커플 선글라스", 'place': "VR 테마파크 또는 오락실"},
                {'mission': "매운 음식 먹으며 땀 빼기", 'item': "스포츠 타월 세트", 'place': "스트레스 풀리는 매운 갈비찜 맛집"}
            ]
        }

    def calculate_match(self, feat1, feat2):
        # 알고리즘 유지
        diff_curv = abs(feat1['curv'] - feat2['curv'])
        diff_len  = abs(feat1['len_ratio'] - feat2['len_ratio'])
        diff_slope= abs(feat1['slope'] - feat2['slope'])

        s_curv = 100 * math.exp(-diff_curv * 2.5)
        s_len  = 100 * math.exp(-diff_len * 2.0)
        s_slope= 100 * math.exp(-diff_slope * 1.0)

        data_score = (s_curv * 0.5) + (s_len * 0.3) + (s_slope * 0.2)
        data_score = data_score * 1.1

        fate_score = random.randint(70, 99)
        final_score = (data_score * 0.7) + (fate_score * 0.3)

        final_score = int(final_score)
        if final_score > 99: final_score = 99
        if final_score < 1: final_score = 1
        return final_score

    def get_result_html(self, score):
        # 1. 메인 텍스트 결정
        if score >= 70:
            key = score // 2
            data = self.high_score_db.get(key, self.high_score_db[35])
        else:
            data = self.default_text

        # 2. 팁 카테고리 결정
        if score >= 90: tier = 'tier_1'
        elif score >= 80: tier = 'tier_2'
        elif score >= 70: tier = 'tier_3'
        else: tier = 'tier_4'

        # 3. 팁 랜덤 선택
        tip_data = random.choice(self.tips_db[tier])

        # HTML 구성
        html = f"""
        <style>
            @import url('https://fonts.googleapis.com/css2?family=Gamja+Flower&family=Noto+Sans+KR:wght@300;500;700&display=swap');

            .couple-container {{
                max-width: 500px; margin: 0 auto;
                font-family: 'Noto Sans KR', sans-serif;
                animation: fadeUp 1.2s ease-out;
            }}

            .couple-card {{
                background: white;
                border-radius: 40px;
                padding: 40px 30px;
                box-shadow: 0 20px 50px rgba(255, 105, 180, 0.15);
                text-align: center;
                border: 1px solid rgba(255, 230, 230, 0.8);
                position: relative; overflow: hidden;
            }}

            .deco-circle {{
                position: absolute; width: 180px; height: 180px;
                background: radial-gradient(circle, rgba(255,200,200,0.4) 0%, rgba(255,255,255,0) 70%);
                top: -50px; right: -50px; border-radius: 50%; z-index: 0;
            }}

            .main-content {{ position: relative; z-index: 1; }}

            .score-title {{ font-size: 1.0em; color: #aaa; letter-spacing: 3px; margin-bottom: 5px; }}
            .score-val {{
                font-size: 6.5em; font-weight: 800;
                background: linear-gradient(120deg, #ff9a9e 0%, #fecfef 99%, #fecfef 100%);
                -webkit-background-clip: text; -webkit-text-fill-color: transparent;
                margin: -10px 0; font-family: 'Gamja Flower', cursive;
                filter: drop-shadow(2px 2px 5px rgba(255,100,100,0.1));
            }}

            .result-title {{
                font-size: 1.8em; font-weight: 700; color: #444; margin-top: 10px;
                font-family: 'Gamja Flower', cursive;
            }}

            .tags {{ margin: 15px 0; }}
            .tag-pill {{
                display: inline-block; background: #fff0f6; color: #d63384;
                padding: 5px 12px; border-radius: 15px; font-size: 0.85em; margin: 2px;
            }}

            .desc-area {{
                margin-top: 20px; padding: 20px;
                background: #fafafa; border-radius: 15px;
                color: #666; line-height: 1.6; font-size: 1.0em;
                text-align: left;
            }}

            /* --- V23.0 Love Tip Section Design --- */
            .tip-container {{
                margin-top: 25px;
                background: linear-gradient(135deg, #fff5f7 0%, #fff 100%);
                border-radius: 20px;
                padding: 20px;
                border: 2px dashed #ffccd5;
                text-align: left;
            }}
            .tip-header {{
                font-family: 'Gamja Flower', cursive;
                font-size: 1.4em; color: #ff6b81; margin-bottom: 15px;
                text-align: center; font-weight: bold;
            }}
            .tip-item {{
                margin-bottom: 12px; display: flex; align-items: flex-start;
            }}
            .tip-icon {{
                min-width: 30px; font-size: 1.2em; margin-right: 8px; text-align: center;
            }}
            .tip-content {{
                font-size: 0.95em; color: #555; word-break: keep-all; line-height: 1.4;
            }}
            .tip-content b {{ color: #d63031; }}

            @keyframes fadeUp {{ from {{ opacity: 0; transform: translateY(20px); }} to {{ opacity: 1; transform: translateY(0); }} }}
        </style>

        <div class="couple-container">
            <div class="couple-card">
                <div class="deco-circle"></div>
                <div class="main-content">
                    <div class="score-title">COMPATIBILITY</div>
                    <div class="score-val">{score}%</div>

                    <div class="result-title">{data['title']}</div>

                    <div class="tags">
                        {' '.join([f'<span class="tag-pill">{t}</span>' for t in data['tag'].split()])}
                    </div>

                    <div class="desc-area">
                        {data['desc']}
                    </div>

                    <div class="tip-container">
                        <div class="tip-header">💘 오늘의 추천 레시피</div>

                        <div class="tip-item">
                            <div class="tip-icon">📝</div>
                            <div class="tip-content"><b>Mission:</b> {tip_data['mission']}</div>
                        </div>
                        <div class="tip-item">
                            <div class="tip-icon">🎁</div>
                            <div class="tip-content"><b>Item:</b> {tip_data['item']}</div>
                        </div>
                        <div class="tip-item">
                            <div class="tip-icon">📍</div>
                            <div class="tip-content"><b>Place:</b> {tip_data['place']}</div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        """
        return html

# =========================================================
# 커플 분석 시각화 클래스 (V22와 동일, 사진 액자 기능 포함)
# =========================================================
class CoupleAnalysisVisualizer:
    def __init__(self, model_path):
        print(f"✅ [커플 매칭 V23.0 Ultimate] 모델 로딩 중: {os.path.basename(model_path)}")
        self.model = YOLO(model_path)
        self.interpreter = CompatibilityInterpreter()
        self.mp_hands = mp.solutions.hands
        self.hands = self.mp_hands.Hands(static_image_mode=True, max_num_hands=1)
        self.target_line_id = 2

    def process_single_image(self, image_path):
        origin_img = cv2.imread(image_path)
        if origin_img is None: return None, None
        img_rgb = cv2.cvtColor(origin_img, cv2.COLOR_BGR2RGB)
        mp_results = self.hands.process(img_rgb)
        height, width = origin_img.shape[:2]
        hand_len = height * 0.5

        if mp_results.multi_hand_landmarks:
            lm = mp_results.multi_hand_landmarks[0].landmark
            p0 = np.array([lm[0].x * width, lm[0].y * height])
            p9 = np.array([lm[9].x * width, lm[9].y * height])
            hand_len = np.linalg.norm(p9 - p0)

        lab = cv2.cvtColor(origin_img, cv2.COLOR_BGR2LAB)
        l, a, b = cv2.split(lab)
        clahe = cv2.createCLAHE(clipLimit=2.0, tileGridSize=(8, 8))
        ai_input = cv2.cvtColor(cv2.merge((clahe.apply(l), a, b)), cv2.COLOR_LAB2BGR)

        results = self.model.predict(ai_input, conf=0.05, verbose=False)
        best_conf = 0; best_kpts = None

        if results and results[0].keypoints is not None:
            kpts_all = results[0].keypoints.xy.cpu().numpy()
            clses = results[0].boxes.cls.cpu().numpy()
            confs = results[0].boxes.conf.cpu().numpy()
            for idx, cls_id in enumerate(clses):
                if int(cls_id) == self.target_line_id:
                    if confs[idx] > best_conf:
                        best_conf = confs[idx]; best_kpts = kpts_all[idx]

        canvas_img = origin_img.copy(); features = None
        if best_kpts is not None:
            points = np.array([(int(x), int(y)) for x, y in best_kpts if x > 0])
            if len(points) > 1:
                cv2.polylines(canvas_img, [points], False, (180, 105, 255), 10, cv2.LINE_AA)
                cv2.polylines(canvas_img, [points], False, (255, 255, 255), 3, cv2.LINE_AA)
                curve_len = np.sum(np.sqrt(np.sum(np.diff(points, axis=0)**2, axis=1)))
                euclidean = np.linalg.norm(points[-1] - points[0])
                vec = points[-1] - points[0]
                slope = vec[1] / (vec[0] + 1e-6)
                features = {'len_ratio': curve_len / hand_len, 'curv': curve_len / (euclidean + 1e-6), 'slope': slope}

        return canvas_img, features

    def _img_to_base64(self, img):
        img_pil = Image.fromarray(cv2.cvtColor(img, cv2.COLOR_BGR2RGB))
        buffered = BytesIO()
        img_pil.save(buffered, format="JPEG", quality=90)
        img_str = base64.b64encode(buffered.getvalue()).decode()
        return img_str

    def display_framed_photos(self, img1, img2):
        img1_b64 = self._img_to_base64(img1)
        img2_b64 = self._img_to_base64(img2)

        html = f"""
        <style>
            .photo-container {{ display: flex; justify-content: center; gap: 20px; margin: 30px 0; }}
            .photo-frame {{
                background: #fff; padding: 10px; border-radius: 20px;
                box-shadow: 0 10px 20px rgba(0,0,0,0.1); text-align: center;
                border: 2px solid #ffebee; width: 45%; max-width: 200px;
            }}
            .photo-frame img {{
                width: 100%; height: auto; aspect-ratio: 1/1; object-fit: cover;
                border-radius: 15px; border: 2px solid #ffcdd2;
            }}
            .photo-label {{
                margin-top: 10px; font-family: 'Gamja Flower', cursive; color: #ff8a80; font-size: 1.2em; font-weight: bold;
            }}
            .heart-divider {{ font-size: 2em; align-self: center; color: #ff6b81; animation: beat 1s infinite; }}
            @keyframes beat {{ 0% {{ transform: scale(1); }} 50% {{ transform: scale(1.2); }} 100% {{ transform: scale(1); }} }}
        </style>
        <div class="photo-container">
            <div class="photo-frame">
                <img src="data:image/jpeg;base64,{img1_b64}">
                <div class="photo-label">Person A</div>
            </div>
            <div class="heart-divider">💖</div>
            <div class="photo-frame">
                <img src="data:image/jpeg;base64,{img2_b64}">
                <div class="photo-label">Person B</div>
            </div>
        </div>
        """
        display(HTML(html))

    def compare_couples(self, file_list):
        if len(file_list) < 2: return
        print(f"💞 커플 분석 진행 중... 두 분의 손을 맞대어 봅니다...")
        img1, feat1 = self.process_single_image(file_list[0])
        img2, feat2 = self.process_single_image(file_list[1])

        if feat1 is None or feat2 is None:
            print("❌ 오류: 감정선을 찾지 못했습니다.")
            return

        self.display_framed_photos(img1, img2)

        match_score = self.interpreter.calculate_match(feat1, feat2)
        html_report = self.interpreter.get_result_html(match_score)
        display(HTML(html_report))

# ==========================================
# 실행
# ==========================================
BASE_PATH = '/content/drive/MyDrive/final_pro/mobileNet'
MODEL_FILE = 'num_02.pt'
model_path = os.path.join(BASE_PATH, MODEL_FILE)

if os.path.exists(model_path):
    vis = CoupleAnalysisVisualizer(model_path)
    file_list = []
    print("\n" + "="*50)
    print("👤 [1단계] 본인(Person A)의 손바닥 사진을 업로드하세요.")
    print("="*50)
    uploaded_1 = files.upload()
    if uploaded_1:
        file_list.append(list(uploaded_1.keys())[0])
        print("✅ 1단계 완료!\n")
        print("="*50)
        print("❤️ [2단계] 상대방(Person B)의 손바닥 사진을 업로드하세요.")
        print("="*50)
        uploaded_2 = files.upload()
        if uploaded_2:
            file_list.append(list(uploaded_2.keys())[0])
            print("✅ 2단계 완료! 결과 계산 중...\n")
            vis.compare_couples(file_list)
        else: print("❌ 상대방 사진이 없습니다.")
    else: print("❌ 본인 사진이 없습니다.")
else:
    print(f"❌ 모델 없음: {model_path}")